runtime: python27
api_version: 1
threadsafe: true

skip_files:
  - "env/"
  - "__pycache__/"

env_variables:
  FLASK_APP: "app.py"

libraries:
  - name: flask
    version: "0.12"
  - name: werkzeug
    version: "0.11.10"
  - name: ssl
    version: "2.7.11"

handlers:
  - url: /static
    static_dir: static

  - url: .*
    script: app
